class StaticVariables:
    Addition_csv = "./src/UnitTests/data/Unit_Test_Addition.csv"
    Subtraction_csv = "./src/UnitTests/data/Unit_Test_Subtraction.csv"
    Multiplication_csv = "./src/UnitTests/data/Unit_Test_Multiplication.csv"
    Division_csv = "./src/UnitTests/data/Unit_Test_Division.csv"
    Square_csv = "./src/UnitTests/data/Unit_Test_Square.csv"
    SquareRoot_csv = "./src/UnitTests/data/Unit_Test_Square_Root.csv"
    val1 = "Value 1"
    val2 = "Value 2"
    result = "Result"
